export {
  PACKAGE_ID,
  SOURCE_VERSION,
  ESA_CCI_CITATION,
  ESA_CCI_DOI,
  ESA_CCI_URL,
  ESA_CCI_START_YEAR,
  ESA_CCI_END_YEAR,
  ESA_CCI_RESOLUTION_KM,
  SCHUUR_2022_CITATION,
  CARBON_STOCK_GT_LOW,
  CARBON_STOCK_GT_HIGH,
  CARBON_STOCK_GT_MID,
  RELEASE_2C_GT_2100_LOW,
  RELEASE_2C_GT_2100_HIGH,
  RELEASE_4C_GT_2100_LOW,
  RELEASE_4C_GT_2100_HIGH,
  MAGT_TREND_C_PER_DECADE,
  CRITICAL_TEMP_LOWER_C,
  FROZEN_THRESHOLD_C,
  NOT_A_BISTABLE_TIPPING_ELEMENT_NOTE,
  SIBERIA_DATA_GAP_NOTE,
  GRACE_UNSUITABLE_NOTE,
} from "./constants.ts";

export {
  ALL_EVIDENCE,
  observationEvidence,
  carbonEvidence,
  isBistableTippingElement,
  isMagtTrendAModelOutput,
  magtTrendCPerDecade,
  esaCciPeriod,
  isGraceSuitableForPermafrostMonitoring,
  hasSiberiaGroundStationDataGap,
  isEsaCciComparativelyLessAffectedBySiberiaGap,
  isSyntheticDataAPerYearMeasurement,
  isCarbonFeedbackACalibratedEmissionsModel,
  carbonStockGtMid,
  carbonStockGtRange,
  isCarbonStockWithinPublishedRange,
  release2cGt2100Range,
  release4cGt2100Range,
  type EvidenceEntry,
  type Stance,
} from "./evidence.ts";

export {
  STANCE_LABEL_DE,
  EVIDENCE_DOI,
  EVIDENCE_URL,
  KEY_NUMBERS,
  stanceLabelDe,
  headlineFor,
} from "./display.ts";
